### ISSUE TITLE
"Get-ChildItem The network path was not found" Error

### ISSUE THREAD

**Issue by sambedingfield** [Indaclouds/LethalCompanyModder#11]
Thanks for the amazing script!
I ran into the error on my machine **Get-ChildItem The network path was not found**.
My Steam games are in a separate drive, nothing else I can think of.
My crewmates didn't get this error.

I'm no PowerShell dev, so I couldn't diagnose why, but I just added another param to manually add my game install:
```
[Parameter(
    HelpMessage = "Path to the 'Lethal Company' folder"
)]
[ValidateScript({ if (Test-Path -Path $_) { $true } else { throw "`"$_`" folder not found." } })]
[string] $SetDir

...

if ($SetDir.Length) {
    # Set game directory from command parameter
    Write-Host "Get directory `"$SetDir`""
    $GameDirectory = $SetDir
} else {
    # Search for directory where Lethal Company is installed
   ...
}
if (-not $GameDirectory) { Write-Error -Message "Lethal Company installation directory not found." }
```

Now the following script works for me:
`& .\LethalCompanyModder.ps1 -SetDir "G:\SteamLibrary\steamapps\common\Lethal Company"`

**Comment by VouDoo** [comment]
Hello @sambedingfield,

First, thanks a lot for your comment. I am glad our script serves you well :)

I am not able to reproduce this issue but it's probably due to a problem with the PS drives objects.

I recommend you to test it with [PowerShell Core edition](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4) instead. Sometimes, PowerShell Desktop edition (the one pre-installed on Windows) has some unpredictable behaviors.

Also, I'm going to add a parameter to set the game directory manually as a parameter very soon.
